---
# tasks file for common
- name: Install software
  become: True
  become_user: root
  apt:
    update-cache: yes
    name: "{{ common_packages }}"
- name: "Maak user {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    comment: "{{ user_full_name }}"
    shell: /bin/bash
    uid: 1040
    groups: adm,sudo
    password: "{{ user_password }}"
- name: Geef users ssh permissie om in te loggen
  copy: 
    dest: /etc/ssh/sshd_config.d/99-cloudimg-settings.conf
    content: |
      PasswordAuthentication yes
- name: Set vi editing mode
  copy: 
    dest: "{{ home }}/.inputrc" 
    content: |
      set editing-mode vi
- name: Remove org.freedesktop.color.polify file
  file:
    path: /usr/share/polkit-1/actions/org.freedesktop.color.policy
    state: absent


