- hosts: ubuntu_desktops
  gather_facts: true
  collections:
    - eelcovv.ldx_webdev_server
  tasks:
    - import_role:
        name: ubuntu_desktop
- hosts: mint_desktops
  gather_facts: true
  collections:
    - eelcovv.ldx_webdev_server
  tasks:
    - import_role:
        name: mint_desktop
