---
# tasks file for mamba
- name: Install base mamba
  vars:
    arch: "{{ mamba_arch }}"
    root_prefix: "{{ mamba_root_prefix }}"
    root_prefix_condarc: "{{ mamba_root_prefix_condarc }}"
    packages: "{{ mamba_base_packages }}"
  ansible.builtin.import_role:
    name: mambaorg.micromamba
- name: Change owner Mamba
  file:
    path: "{{ mamba_root_prefix }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    recurse: True
- name: Run Mamba init
  shell: "{{ mamba_root_prefix }}/bin/mamba init --system"
  args:
    creates: /etc/profile.d/conda.sh