---
# tasks file for ubuntu-desktop
- name: Install software for desktop
  become: True
  become_user: root
  apt:
    update-cache: yes
    name: "{{ desktop_packages }}"
- name: Adding xrdp user to group ssl-cert
  user:
    name: 'xrdp' 
    groups: ssl-cert
    append: yes
- name: Install pycharm with snap
  ansible.builtin.import_role:
    name: oefenweb.pycharm
- name: Copy Pycharm Desktop icon
  file:
    path: "{{ role_path }}/files/PyCharm.desktop"
    dest: "{{ home }}/Desktop/PyCharm.desktop"
    mode: "0775"
    owner: "{{ user }}"
    group: "{{ user }}"


